### ISSUE TITLE
Shift button on demo doesn't work as described

### ISSUE THREAD

**Issue by geoidesic** [GetmeUK/ContentTools#367] opened 2016-12-20 12:47 UTC
Using Chrome on Mac Yosemite... the text says "hold down shift and after a few seconds you'll see pulsing borders on editable elements"... that doesn't happen. http://getcontenttools.com/demo

**Comment by anthonyjb** [comment] 2016-12-23 11:11
Hi @geoidesic - thanks I'll take a look into this.

**Comment by anthonyjb** [comment] 2017-07-27 09:09
@geoidesic I've finally had chance to test this on Chrome / Mac Yosemite and it works as described and I'm unable to reproduce the issue. Closing for now but will happily reopen if someone can provide me with instructions to reproduce.

**Closed by anthonyjb** 2017-07-27 09:09 UTC
Labels: bug, invalid, Minor
