### ISSUE TITLE
if i am end of blog and select tool code for write then how can i select new tool?

### ISSUE THREAD

**Issue by makasanas** [GetmeUK/ContentTools#200] opened 2016-04-29 05:07 UTC
http://prntscr.com/ay6d00 you can look this screenshoot what is real problem if i am at and of the blog and select write code then after i can't go for new line i think set event if code is selected and any one hit enter two time then go to select new tool.

**Comment by anthonyjb** [comment] 2016-04-29 10:20
Hi @makasanas,

This is perfect thank you - the solution is to hold the Ctrl-key down (Cmd on Apple) and click the (P)aragraph tool, this will create a new paragraph rather and converting the current editable block.

There's a note on it here on the demo page http://getcontenttools.com/demo#adding-and-converting-content

Duplicate of https://github.com/GetmeUK/ContentTools/issues/114

**Closed by anthonyjb** 2016-04-29 10:20 UTC
Labels: duplicate, question
