### ISSUE TITLE
A lot of bugs...

### ISSUE THREAD

**Issue by SimBioT1954** [GetmeUK/ContentTools#172] opened 2016-03-26 04:44 UTC
Hello!
I've got a lot of bugs in content-tools:
Click pencil icon → Ctrl + a → save (green icon "ct-ignition__button--confirm") 
after this I still stay in edit mode:
![img](https://cloud.githubusercontent.com/assets/11522338/14058022/18e349da-f323-11e5-8056-3a73fef915b2.png)

Also: 
Click pencil icon → double-click any image — the same problem:
![img2](https://cloud.githubusercontent.com/assets/11522338/14058094/73242c4a-f326-11e5-9a92-bf85b1e3e228.png)

**Comment by anthonyjb** [comment] 2016-03-26 13:19
Hi @SimBioT1954 this is a duplicate of issue #171 and has been fixed, this was a bug introduced in the release 1.2 that prevented the page being reverted to a non-editable state when saved with no changes. It's now resolved.

**Closed** 2016-03-26 13:20 UTC
Labels: duplicate
