### ISSUE TITLE
Editor does not load demo in Edge

### ISSUE THREAD

**Issue by ElijahFowler** [GetmeUK/ContentTools#259] opened 2016-06-29 23:05 UTC
Hi,

I noticed that the editor in the demo does not load when you click the pencil in Microsoft Edge, UNLESS you have the dev tools open, which seems really weird.  No errors thrown, it just doesn't load (spinning gear).

I tried it on 3 different computers (owned by different people) with the same results.

Edge version 25.10586.0.0

**Comment by anthonyjb** [comment] 2016-06-29 23:18
I thought this error had been resolved :/ looks like it hasn't - there's a full description of the behaviour here and the hack I implemented. #258 

If you're able to help identify the cause of the issue that would be very helpful as I'm a linux user and don't have access to IE Edge other than via BrowserStack which is hard going for bugs of this nature.

It's a fool hardy thing to say but I'm beginning to suspect that it may be an issue with Edge as there's just no pattern to the error being triggered - added to which on Browser stack my hack appeared to work and the original poster of the issue reported it was working for him after the hack also - so appears maybe just refreshing the page removes the issue.

**Comment by anthonyjb** [comment] 2016-06-29 23:38
It maybe related to this issue https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6664966/ Although not strictly the same the description of the symptoms is pretty much identical.

**Comment by anthonyjb** [comment] 2016-06-30 08:46
I think it maybe related to this Edge issue https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6664966/ (at least the description of the issue sounds similar if not the set up).

**Comment by concept-core** [comment] 2016-07-01 07:32
@anthonyjb is your code being compiled to ES6 ? 
the tickets has a reaction where is being mentioned that ES5 works in edge and Es6 is kinda broken.

**Comment by anthonyjb** [comment] 2016-07-01 07:34
No it doesn't - it's only the symptoms that are similar the possible reason they mention (i.e es6/es5) is different, it's just the only issue that's seems the same. I'll have a windows box and edge over the weekend hopefully so I can try to fix it.

**Comment by bfintal** [comment] 2016-07-05 18:26
I also just started to experience this. I'm on a Mac so I can't currently test this, but I had our tester do some tests on her machine. I'm not too sure about what to think about this finding.

One way to replicate (at least in Page Builder Sandwich):
1. Create an empty document with CT,
2. Write some short text, then save, and reload the page (CT should still work)
3. Edit again, but now write more text until it wraps to the next line; then save, and reload the page (CT should stop working).

As with the OP said, it begins working when you have dev tools open.

**Comment by anthonyjb** [comment] 2016-07-05 18:35
I can reproduce it on IE Edge consistently though it falls over on different parts of the content. I meant to get some time on it today but left the office earlier than intended - will get time on it tomorrow.

**Comment by bfintal** [comment] 2016-07-05 18:37
We are on a holiday tomorrow, but we can test your patch on Thursday when we're back in the office.

**Comment by bfintal** [comment] 2016-07-05 18:57
We'll also test the fix stated in #258 on Thursday and report back

**Comment by bfintal** [comment] 2016-07-07 12:40
Just tested #258, the patch worked for us during tests.

**Comment by anthonyjb** [comment] 2016-07-10 08:27
@bfintal just to confirm - does the issue no longer occur for you? The patch discussed in #258 is in the current version current master branch and on the ContentTools website editor.

**Comment by bfintal** [comment] 2016-07-11 08:01
@anthonyjb Okay just heard back from our tester. She tested http://getcontenttools.com/demo in Edge and it hangs after clicking the edit/pencil button when the console is closed. When the console is open, the editor starts, but as soon as one of the buttons are pressed (e.g. right-aligning), it errors out. Saying that `addTags` is undefined (which I think refers to the patch you're going to add in #258)

**Comment by anthonyjb** [comment] 2016-07-11 08:29
@bfintal so the patch you reference #258 that is in the current master branch - so it's added (just not in the current release) and in place on the sites demo page so unfortunately the issue remains, have some more time today to review, if there's any chance of a full console output for the error that would be great.

**Comment by ElijahFowler** [comment] 2016-10-17 17:58
So the demo seems to be working now in version 38.14393.0.0, can anyone confirm?

**Comment by anthonyjb** [comment] 2016-10-18 16:46
I no longer see an issue in the latest build on browserstack - I'm going to close this issue for now and will reopen if anyone else reports it.

**Closed by anthonyjb** 2016-10-18 16:46 UTC
Labels: bug, help wanted
