### ISSUE TITLE
Disable Rich Text Options

### ISSUE THREAD

**Issue by dominicr** [GetmeUK/ContentTools#79] opened 2015-12-12 10:32 UTC
Is it possible already, or to add in, the ability to turn off styling options for specific areas of text, using an extra data attribute?

Use case: On an editable page there are regions, such as headings, where I don't want a user to be able to apply formatting beyond plain text as to do so would break the design. On other sections of the page the editor should be able to use the full rich text toolbar.

I haven't been able to find a way of doing this in the documentation. If it is in there then maybe it should be highlighted on the demo page.

Thank you.

**Comment by anthonyjb** [comment] 2015-12-13 16:26
Hi @dominicr - There's no way to do this right now. I'm working on a new editable element currently (`ContentEdit.Field`) which will act a lot more like a form field for editable content that is less free form and more purposeful, e.g a blog article heading, date, etc.

In the meantime whilst there's no clean solution that comes to mind if it's something you need urgently then one approach would be to be to update the toolbox code here: https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/toolbox.coffee#L448 to check for a special attribute against an element as you suggested, e.g:

```CoffeeScript
    if @tool.canApply(element, selection) and element.attributes()['data-no-edit'] is undefined
        @disabled(false)
    else
        @disabled(true)
        return
```

We also require this functionality for a current project so it is a confirmed feature.

**Comment by frankbardon** [comment] 2016-02-22 18:32
@anthonyjb: Is there currently an estimated timeline on your version of this feature, and is there anything I can do to help speed that timeline up? We've currently integrated ContentTools into our CMS (open sourcing at a later date) and it would be nice to, for instance, edit blog post titles without leaving the page or popping a modal. I am more than willing to help, just need to make sure I'm not duplicating effort.

**Comment by anthonyjb** [comment] 2016-02-23 09:17
Hi @frankbardon 

So currently I'm working on a CMS project for a client that requires the `ContentEdit.Field` functionality that's described, the deadline for the project is end of March so I would hope to have a working draft ready in the next 4-6 weeks.

Having said that I'm not opposed to some help (in fact I'd be grateful of it). If you think you have some time to spare on the issue perhaps we can plan and agree on an interface for the new `ContentEdit.Field` class here before moving on to create it.

As it stands my requirements for the `ContentEdit.Field` class are:

- to support validation of the content
- to allow an error to be set against the field directly (so that server-side validation can be reflected)
- to support tool configuration (exactly how is a bit of a question since the class will reside in `ContentEdit` and tools reside in `ContentTools` and I don't want to tightly couple them, however it could be a suggested tool set that ContentTools or other UIs can interpret for themselves.

The tag type itself wouldn't matter in this case and we'd always use a custom tag attribute to flag that an element was a field, e.g something along the lines of:

```
<time data-ce-tag="field">11:00</time>
```

That's at least a starting point, if you add in your requirements thoughts then we can make sure we achieve everything in the new class.

**Comment by frankbardon** [comment] 2016-02-23 15:04
@anthonyjb Absolutely, I'd definitely be willing.

### Content validation
There is a [fantastic validation library](https://www.npmjs.com/package/validator) we'd be able to incorporate, it supports almost every concern I've had on previous projects. It's strictly a string sanitization/validation library, so there would not really be a code-dance you'd have to do around it in order to sync it to your content. Using this library, we could create either configuration or data attributes that point the `save()` hook where it needs to be. Essentially, an API hook into the validator library.

### Error setting
You have done a fantastic job on the aesthetic, in terms of how interaction and display concerns take place. So, as far as this is concerned, I would definitely leave the "how" of an field error would take place to you.

### Configuration
Absolutely, the decoupling is exactly why I picked this library for our use here. We could do a bit of environment detection inside of `ContentTools` allowing it to optionally decide to add field's relevant tooling. I'd just be wary of enforcing how these tools detect where they are placed.

To give you a bit of background on what I'm up to with ContentTools...

We're developing a CMS (not far from some of your video demos) using Symfony CMF as the backend. Symfony CMF uses CreatePHP as it's REST interface for saving frontend content to the backend. ContentTools allowed me to use the RDFa HTML annotations produced by CreatePHP and initialize the tool on top of those.

Now, this poses an interesting issue in terms of creating field level editing... The tags would be formatted something like this `h1` at the field level.

```html
<div about="/cms/content/home" typeof="schema:WebPage" xmlns:schema="http://schema.org/">
    <h1 property="schema:headline">The Title</h1>
    <div property="schema:text">
        <h2>Welcome to the Symfony CMF Demo</h2>
        <p>If you see this page, it means that the...</p>
    </div>
</div>
```

I've hooked into the `div` by first reading the main `div` and grabbing the `about, typeof and xmlns:schema` properties on `init` and using them in the `save` hook to create a response. I iterate through all `property^="schema:"` tags and post their content to the backend. That works perfectly for how ContentTools works right now.

The backend already supports sending the `h1` as a field, so that's not a concern. We would just need to ensure that the enforcement of validation (and configuration of that validation) is not strictly tied to the markup surrounding the content in question.

**Comment by anthonyjb** [comment] 2016-02-26 08:32
Hi @frankbardon, thanks for the information and in particular the example and explanation of how your hooking in currently - I like this approach and it's similar to what I had in mind the use of the WebPage schema though is very interesting.

I'm playing around with a few different models/approaches for setting up content fields at the moment in particular how we hook in validation libraries without resorting to lots of custom mark up.  Over the weekend I hope to post a draft/example API snippet against the issue based on your comments. 

One question I do keep coming back to is whether or not validation should be performed on the frontend, we have an older version of CT we us in house (much older) that supported validation server and client side. Towards the end of it's life though we switched to always validating server side but instead of waiting for submission we used AJAX to request validation of a field in advance. This has the benefit of only having to write the validation code in one place and removing potential inconsistencies between the two - however potentially it's a more complex approach if you require real-time validation (but I do think client side validation at least should be optional perhaps, based on whether you hook in a validation library like the one you've mentioned).

**Comment by frankbardon** [comment] 2016-02-26 13:26
@anthonyjb I think both approaches have merit. Typically, I use a combination of server and client validation... This could be handled by a generic validation lifecycle hook in the right place that allows a developer to do the actual validation; whether it's server or client side. I guess a decision here could be to do less, but give the developer the job of validating as they see fit. Food for thought.

**Comment by Qqwy** [comment] 2016-03-04 16:13
For my project this is a large requirement as well. I'd love to help if I'm able to.

As for the validation approach, I'd suggest to Keep It Simple, and proclaim that 'real time server validation' is something that is very project-specific. When it is possible to attach a callback to a *content changed* event, and fire a *validation failed* or *validation succeeded* event on the same element, I believe this is enough to support any kind of advanced validation schemes.

Upon re-reading @frankbardon 's post, I think we're pretty much leaning towards the same direction.

**Comment by Qqwy** [comment] 2016-03-05 16:55
Has there already been work done on this? If so, is there a (possibly highly unstable) branch that we could check out and tinker with?

**Comment by anthonyjb** [comment] 2016-04-01 17:25
For those of you following this issue we are making head way, release 1.2.2 introduces element behaviours (which you can read about here http://getcontenttools.com/api/content-edit#behaviours). This is an important step in being able to provide control over the layout of editable content and in the next minor release I'm planning to finish integrating this with ContentTools so that the editor respects the behaviour flags set for elements (e.g the remove tool wont remove an element where the remove behaviour flag is set to false).

Internally we have a deadline to have a first draft implementation of this feature in place for the 15th of April so I expect to have a release out that week which resolves this issue.

Thanks for your patience :)

**Comment by anthonyjb** [comment] 2016-04-24 13:32
For all those interested the latest release [1.2.4](https://github.com/GetmeUK/ContentTools/releases/tag/1.2.4) now contains an early version of fixtures which support standalone fixed position elements on the page.

There's still quite a bit to do before I'll be documenting and recommending people use fixtures is live projects but if you want to have a play there's an example fixture in the ContentEdit sandbox now.

**Comment by anthonyjb** [comment] 2016-05-10 16:21
Another update on fixtures - release [1.2.5](https://github.com/GetmeUK/ContentTools/releases/tag/1.2.5) now provides a working sandbox demo where the title is a Fixture. This is quite a big release in terms of changes though the API is uneffected.

I'm hoping to use fixtures in a current project and over the next 2-3 weeks bring them to a point where I have something stable I can publish as a minor release with documentation.

I'm away for the next couple of weeks but will be checking in so any questions/feedback here or on gitter about fixtures I'll be happy to try and help with.

**Comment by mmoskal** [comment] 2016-06-27 20:58
Seems to work nicely with `<h1>`, `<h3>`, but I couldn't get it to work on `<footer>`, `<span>`, or `<div>`.

**Comment by anthonyjb** [comment] 2016-06-27 21:38
Hi @mmoskal - those aren't tags registered as editable text elements, you'd need to either register them or set a different tag against them, e.g:

```html
<footer data-ce-tag="p">...</footer>
```

**Comment by mmoskal** [comment] 2016-06-27 21:43
Thanks, I will do that!

Out of curiosity, is it due to internals, or is it intentional? If one can only edit plain text in fixtures, it shouldn't matter what is the enclosing tag?

**Comment by anthonyjb** [comment] 2016-06-27 21:52
Fixtures aren't a separate element as such they effectively wrap an existing editable element type in a fixed region, for the fixture to know what type of element it is wrapping it still needs to either recognize the element tag, or be assigned a replacement.

If you don't want the `data-ce-tag` against your footer you can register the `footer` tag as an editable text element, for example:

```JS
ContentEdit.TagNames.get().register(ContentEdit.Text, ['footer']);
```

In the future I want to trial supporting for other element types within fixtures such as images, hence fixtures wrap existing elements rather than functioning as a separate element.

**Comment by anthonyjb** [comment] 2016-06-27 21:55
Having said that might not be a bad shout to default to a text element if the tag isn't recognized for fixtures? @mmoskal

**Comment by mmoskal** [comment] 2016-06-28 09:45
@anthonyjb - yes this sounds like a good idea and thank you for detailed explanation. I'm building a GitLab-based CMS and finding ContentTools great!

**Comment by anthonyjb** [comment] 2017-08-16 10:39
I'm closing this issue now as support for Text and Image fixtures is now present with ContentTools/ContentEdit - which at least to the extent I require resolves this feature. I understand there will be people who still find functionality/features they want missing but I think these are best handled as new issues - thanks all for your patience with this issue.

**Closed by anthonyjb** 2017-08-16 10:39 UTC
Labels: enhancement, question
